name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Start PostgreSQL and Spring Boot using Docker Compose
        run: |
          docker-compose -f backend/docker-compose.yml up -d

      - name: Wait for services to start
        run: |
          docker-compose -f backend/docker-compose.yml ps
          docker-compose -f backend/docker-compose.yml logs -t --tail 100

      - name: Build with Maven
        run: docker-compose -f backend/docker-compose.yml exec backend mvn -f backend/pom.xml clean package

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          tags: naceg/backend-app:latest
          build-args: |
            ARG_NAME=value   # Add build arguments if required
          file: backend/Dockerfile  # Specify the path to your Dockerfile relative to the context

      - name: Stop and remove containers
        run: docker-compose -f backend/docker-compose.yml down
